"""Compose the final synthesis using only TRUE-verified claims."""

import logging
from typing import Any

from langchain_core.runnables import RunnableConfig

from config import get_model
from llm import LLMInvocationError, invoke_text_chain
from models import Claim, PipelineState, build_error_record
from nodes.runtime_config import runtime_language

logger = logging.getLogger(__name__)


def _all_claims(state: PipelineState) -> list[Claim]:
    """Return all claims generated by all analyst lanes."""
    return (
        state["left_claims"]
        + state["centrist_claims"]
        + state["right_claims"]
        + state["people_claims"]
    )


def _true_claims(state: PipelineState) -> list[Claim]:
    """Filter all claims to only those with a TRUE fact-check verdict."""
    all_claims = _all_claims(state)
    verdict_by_text = {
        fact_check.claim.text.strip(): fact_check.verdict.strip().upper()
        for fact_check in state["fact_checks"]
        if fact_check.claim.text.strip()
    }

    true_claims: list[Claim] = []
    seen_texts: set[str] = set()

    for claim in all_claims:
        text = claim.text.strip()
        if not text or text in seen_texts:
            continue
        if verdict_by_text.get(text) == "TRUE":
            true_claims.append(claim)
            seen_texts.add(text)

    # Keep TRUE verdict claims even if wording differs slightly from analyst output.
    for fact_check in state["fact_checks"]:
        text = fact_check.claim.text.strip()
        if not text or text in seen_texts:
            continue
        if fact_check.verdict.strip().upper() != "TRUE":
            continue
        true_claims.append(Claim(text=text, source_ids=fact_check.claim.source_ids))
        seen_texts.add(text)

    return true_claims


def _ensure_short_answer_prefix(synthesis: str, language: str) -> str:
    """Ensure synthesis first line starts with the expected short-answer prefix."""
    lines = [line.strip() for line in synthesis.splitlines() if line.strip()]
    if not lines:
        return ""

    if language == "polish":
        prefix = "Krotka odpowiedz:"
    else:
        prefix = "Short answer:"

    first_line = lines[0]
    lowered_first = first_line.lower()
    if lowered_first.startswith("short answer:") or lowered_first.startswith(
        "krotka odpowiedz:"
    ):
        return "\n".join(lines)

    lines[0] = f"{prefix} {first_line}"
    return "\n".join(lines)


def _fallback_for_no_true_claims(language: str) -> str:
    """Return deterministic synthesis when no TRUE claims exist."""
    if language == "polish":
        return (
            "Krotka odpowiedz: Brak odpowiedzi opartej na zweryfikowanych twierdzeniach TRUE.\n"
            "Wynik koncowy moze opierac sie tylko na twierdzeniach z werdyktem TRUE, a takich nie wykryto."
        )
    return (
        "Short answer: No answer can be supported by verified TRUE claims.\n"
        "The final response is restricted to claims with verdict TRUE, and none were available."
    )


def _fallback_from_true_claims(true_claims: list[Claim], language: str) -> str:
    """Return deterministic synthesis when the LLM synthesis call fails."""
    claims_block = "\n".join(f"- {claim.text}" for claim in true_claims)
    first_claim = true_claims[0].text if true_claims else ""
    if language == "polish":
        return (
            f"Krotka odpowiedz: Na podstawie zweryfikowanych twierdzen TRUE, {first_claim}\n"
            f"Zweryfikowane twierdzenia TRUE:\n{claims_block}"
        )
    return (
        f"Short answer: Based on verified TRUE claims, {first_claim}\n"
        f"Verified TRUE claims:\n{claims_block}"
    )


def compose_final_agent(
    state: PipelineState,
    config: RunnableConfig | None = None,
) -> dict[str, Any]:
    """Generate final synthesis from TRUE-verified claims only."""
    language = runtime_language(state, config)
    true_claims = _true_claims(state)
    logger.info(
        "Compose final: total_claims=%d true_claims=%d fact_checks=%d",
        len(_all_claims(state)),
        len(true_claims),
        len(state["fact_checks"]),
    )

    if not true_claims:
        return {"synthesis": _fallback_for_no_true_claims(language)}

    true_claims_block = "\n".join(
        f"- {claim.text} (Sources: {', '.join(claim.source_ids) if claim.source_ids else 'none'})"
        for claim in true_claims
    )
    response_language = "Polish" if language == "polish" else "English"
    model_name = get_model("compose_final")

    try:
        synthesis = invoke_text_chain(
            system_prompt=(
                "You are a precise final-answer agent. "
                "Use only TRUE-verified claims provided by the pipeline."
            ),
            human_prompt=(
                "User query: {query}\n\n"
                "TRUE-verified claims:\n{true_claims_block}\n\n"
                "Task: Answer the user query directly using only the TRUE-verified claims above.\n"
                "Requirements:\n"
                "- Write in {response_language}.\n"
                "- First line must be: 'Short answer: ...'.\n"
                "- Do not use claims that are not in the TRUE list.\n"
                "- Include source IDs in the rationale when available.\n"
                "- If the TRUE claims are still insufficient for a precise answer, explicitly say so."
            ),
            variables={
                "query": state["query"],
                "true_claims_block": true_claims_block,
                "response_language": response_language,
            },
            temperature=0.0,
            model=model_name,
            config=config,
        )
    except LLMInvocationError as exc:
        logger.warning("Compose final: LLM synthesis failed, using fallback: %s", exc)
        return {
            "synthesis": _fallback_from_true_claims(true_claims, language),
            "errors": [build_error_record("compose_final", exc)],
        }
    synthesis = _ensure_short_answer_prefix(synthesis.strip(), language)

    return {"synthesis": synthesis}
