"""Compose the final synthesis using weighted fact-check results."""

import json
import logging
from typing import Any, cast

from langchain_core.runnables import RunnableConfig
from pydantic import BaseModel, field_validator

from config import get_model
from llm import invoke_structured_chain
from models import Claim, FactCheckResult, PipelineState
from nodes.runtime_config import runtime_language

logger = logging.getLogger(__name__)


class SynthesisOutput(BaseModel):
    """Structured output for final synthesis."""

    synthesis: str = ""

    @field_validator("synthesis", mode="before")
    @classmethod
    def _coerce_synthesis_to_text(cls, value: Any) -> str:
        """Normalize non-string synthesis payloads into text."""
        if isinstance(value, str):
            return value
        if isinstance(value, dict):
            lines: list[str] = []
            for key, nested in value.items():
                label = key.replace("_", " ").strip().capitalize()
                if isinstance(nested, str):
                    lines.append(f"{label}: {nested}")
                else:
                    lines.append(f"{label}: {json.dumps(nested, ensure_ascii=False)}")
            return "\n".join(lines)
        if isinstance(value, list):
            return "\n".join(str(item) for item in value)
        return str(value)


class AlignmentOutput(BaseModel):
    """Structured output for answer-query alignment validation."""

    synthesis: str = ""

    @field_validator("synthesis", mode="before")
    @classmethod
    def _coerce_synthesis_to_text(cls, value: Any) -> str:
        return SynthesisOutput._coerce_synthesis_to_text(value)


def _all_claims(state: PipelineState) -> list[Claim]:
    """Return all claims generated by all analyst lanes."""
    return (
        state["left_claims"]
        + state["centrist_claims"]
        + state["right_claims"]
        + state["people_claims"]
    )


def _normalize_verdict(verdict: str) -> str:
    """Normalize old and new verdict labels for prompt/render compatibility."""
    normalized = verdict.strip().upper().replace("-", "_").replace(" ", "_")
    if normalized == "PARTIALLY_TRUE":
        return "PARTIALLY_TRUE"
    if normalized in {"TRUE", "CONTESTED", "UNVERIFIED"}:
        return normalized
    if normalized in {"MISLEADING", "FALSE"}:
        return "UNVERIFIED"
    return normalized or "UNVERIFIED"


def _usable_fact_checks(state: PipelineState) -> list[FactCheckResult]:
    """Return fact-checks usable for final synthesis, weighted by confidence."""
    usable: list[FactCheckResult] = []
    seen_texts: set[str] = set()
    for fact_check in state["fact_checks"]:
        text = fact_check.claim.text.strip()
        if not text or text in seen_texts:
            continue
        verdict = _normalize_verdict(fact_check.verdict)
        confidence = fact_check.confidence
        if not confidence:
            if verdict == "TRUE":
                confidence = 0.85
            elif verdict == "PARTIALLY_TRUE":
                confidence = 0.65
            elif verdict == "CONTESTED":
                confidence = 0.40
            else:
                confidence = 0.20
        if confidence < 0.30:
            continue
        usable.append(
            FactCheckResult(
                claim=fact_check.claim,
                verdict=verdict,
                rationale=fact_check.rationale,
                confidence=confidence,
                supporting_sources=fact_check.supporting_sources,
                contradicting_sources=fact_check.contradicting_sources,
            )
        )
        seen_texts.add(text)
    return sorted(usable, key=lambda item: item.confidence, reverse=True)


def _ensure_short_answer_prefix(synthesis: str, language: str) -> str:
    """Ensure synthesis first line starts with the expected short-answer prefix."""
    lines = [line.strip() for line in synthesis.splitlines() if line.strip()]
    if not lines:
        return ""

    if language == "polish":
        prefix = "Krotka odpowiedz:"
    else:
        prefix = "Short answer:"

    first_line = lines[0]
    lowered_first = first_line.lower()
    if lowered_first.startswith("short answer:") or lowered_first.startswith(
        "krotka odpowiedz:"
    ):
        return "\n".join(lines)

    lines[0] = f"{prefix} {first_line}"
    return "\n".join(lines)


def _fallback_for_no_usable_claims(language: str) -> str:
    """Return deterministic synthesis when no sufficiently supported claims exist."""
    if language == "polish":
        return (
            "Krotka odpowiedz: Brak odpowiedzi opartej na wystarczajaco zweryfikowanych twierdzeniach.\n"
            "Dostepne twierdzenia maja zbyt niska pewnosc albo wymagaja dodatkowych zrodel."
        )
    return (
        "Short answer: No answer can be supported by sufficiently verified claims.\n"
        "The available claims have too little confidence or need additional sources."
    )


def _fallback_from_weighted_claims(
    fact_checks: list[FactCheckResult], language: str
) -> str:
    """Return deterministic synthesis when the LLM synthesis call fails."""
    claims_block = "\n".join(
        f"- [{item.verdict}, {item.confidence:.2f}] {item.claim.text}"
        for item in fact_checks
    )
    first_claim = fact_checks[0].claim.text if fact_checks else ""
    if language == "polish":
        return (
            f"Krotka odpowiedz: Na podstawie wazonych twierdzen, {first_claim}\n"
            f"Wazone twierdzenia:\n{claims_block}"
        )
    return (
        f"Short answer: Based on weighted verified claims, {first_claim}\n"
        f"Weighted claims:\n{claims_block}"
    )


def _render_weighted_claims(fact_checks: list[FactCheckResult]) -> str:
    """Render weighted fact-checks for the compose prompt."""
    lines: list[str] = []
    for item in fact_checks:
        sources = (
            item.supporting_sources
            or item.claim.source_ids
        )
        contradicting = ", ".join(item.contradicting_sources) or "none"
        lines.append(
            f"- Verdict: {_normalize_verdict(item.verdict)}; Confidence: {item.confidence:.2f}; "
            f"Claim: {item.claim.text}; Supporting sources: {', '.join(sources) if sources else 'none'}; "
            f"Contradicting sources: {contradicting}; Rationale: {item.rationale}"
        )
    return "\n".join(lines)


def _align_answer_to_query(
    *,
    query: str,
    synthesis: str,
    weighted_claims_block: str,
    response_language: str,
    model_name: str,
) -> str:
    """Run a lightweight answer-to-query alignment pass."""
    data = invoke_structured_chain(
        schema=AlignmentOutput,
        system_prompt="You validate whether a final political analysis answers the user's question.",
        human_prompt=(
            "User asked: {query}\n\n"
            "Draft answer:\n{synthesis}\n\n"
            "Available weighted claims:\n{weighted_claims_block}\n\n"
            "Task: If the draft directly answers the user, return it unchanged. "
            "If it partially answers, append a short Note section listing unanswered aspects. "
            "If it misses the question, rewrite it to answer directly using only the weighted claims. "
            "Write in {response_language}. Return JSON with exactly one key: synthesis."
        ),
        variables={
            "query": query,
            "synthesis": synthesis,
            "weighted_claims_block": weighted_claims_block,
            "response_language": response_language,
        },
        temperature=0.0,
        model=model_name,
    )
    alignment = cast(AlignmentOutput, data)
    return alignment.synthesis.strip()


def compose_final_agent(
    state: PipelineState,
    config: RunnableConfig | None = None,
) -> dict[str, Any]:
    """Generate final synthesis from weighted verified claims."""
    language = runtime_language(state, config)
    usable_fact_checks = _usable_fact_checks(state)
    logger.info(
        "Compose final: total_claims=%d usable_fact_checks=%d fact_checks=%d",
        len(_all_claims(state)),
        len(usable_fact_checks),
        len(state["fact_checks"]),
    )

    if not usable_fact_checks:
        return {"synthesis": _fallback_for_no_usable_claims(language)}

    weighted_claims_block = _render_weighted_claims(usable_fact_checks)
    response_language = "Polish" if language == "polish" else "English"
    model_name = get_model("compose_final")

    try:
        data = invoke_structured_chain(
            schema=SynthesisOutput,
            system_prompt=(
                "You are a precise final-answer agent. "
                "Use only weighted fact-checked claims provided by the pipeline."
            ),
            human_prompt=(
                "User query: {query}\n\n"
                "Weighted fact-checked claims:\n{weighted_claims_block}\n\n"
                "Task: Answer the user query directly using the weighted claims above.\n"
                "Requirements:\n"
                "- Write in {response_language}.\n"
                "- First line must be: 'Short answer: ...'.\n"
                "- Do not use claims that are not in the weighted claims list.\n"
                "- HIGH confidence claims (0.8+) may be stated as established fact.\n"
                "- MEDIUM confidence claims (0.5-0.8) must be qualified.\n"
                "- CONTESTED claims (0.3-0.5) must present the disagreement.\n"
                "- Include source IDs in the rationale when available.\n"
                "- If the claims are insufficient for a precise answer, explicitly say so.\n"
                "Return JSON with exactly one key: synthesis (string)."
            ),
            variables={
                "query": state["query"],
                "weighted_claims_block": weighted_claims_block,
                "response_language": response_language,
            },
            temperature=0.0,
            model=model_name,
        )
    except Exception as exc:
        logger.warning("Compose final: LLM synthesis failed, using fallback: %s", exc)
        return {
            "synthesis": _fallback_from_weighted_claims(
                usable_fact_checks, language
            )
        }
    synthesis_data = cast(SynthesisOutput, data)
    synthesis = _ensure_short_answer_prefix(synthesis_data.synthesis.strip(), language)

    try:
        aligned = _align_answer_to_query(
            query=state["query"],
            synthesis=synthesis,
            weighted_claims_block=weighted_claims_block,
            response_language=response_language,
            model_name=model_name,
        )
        if aligned:
            synthesis = _ensure_short_answer_prefix(aligned, language)
    except Exception as exc:
        logger.warning("Compose final: alignment check failed, keeping draft: %s", exc)

    return {"synthesis": synthesis}
